// autogenerated by sql-generate v1.0.0 on Thu Dec 17 2015 16:49:26 GMT+0000 (UTC)

var sql = require('sql');


/**
 * SQL definition for public.alexa_rank_cache
 */
exports.alexa_rank_cache = sql.define({
	name: 'alexa_rank_cache',
	columns: [
		{ name: 'site_domain' },
		{ name: 'rank' },
		{ name: 'download_date' }
	]
});


/**
 * SQL definition for public.expression_domain_annotations
 */
exports.expression_domain_annotations = sql.define({
	name: 'expression_domain_annotations',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'territoire_id' },
		{ name: 'expression_domain_id' },
		{ name: 'user_id' },
		{ name: 'media_type' },
		{ name: 'emitter_type' },
		{ name: 'estimated_potential_audience' },
		{ name: 'keywords' }
	]
});


/**
 * SQL definition for public.expression_domains
 */
exports.expression_domains = sql.define({
	name: 'expression_domains',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'main_url' },
		{ name: 'title' },
		{ name: 'description' },
		{ name: 'keywords' }
	]
});


/**
 * SQL definition for public.expressions
 */
exports.expressions = sql.define({
	name: 'expressions',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'main_html' },
		{ name: 'main_text' },
		{ name: 'title' },
		{ name: 'html_lang' },
		{ name: 'meta_description' },
		{ name: 'meta_keywords' },
		{ name: 'publication_date' },
		{ name: 'h1' },
		{ name: 'h2' },
		{ name: 'h3' },
		{ name: 'h4' },
		{ name: 'h5' },
		{ name: 'h6' },
		{ name: 'strong' },
		{ name: 'em' },
		{ name: 'b' },
		{ name: 'i' }
	]
});


/**
 * SQL definition for public.lifecycle
 */
exports.lifecycle = sql.define({
	name: 'lifecycle',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' }
	]
});


/**
 * SQL definition for public.links
 */
exports.links = sql.define({
	name: 'links',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'source' },
		{ name: 'target' }
	]
});


/**
 * SQL definition for public.oracle_credentials
 */
exports.oracle_credentials = sql.define({
	name: 'oracle_credentials',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'credentials' },
		{ name: 'oracle_id' },
		{ name: 'user_id' }
	]
});


/**
 * SQL definition for public.oracles
 */
exports.oracles = sql.define({
	name: 'oracles',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'oracle_node_module_name' },
		{ name: 'options' },
		{ name: 'credentials_infos' }
	]
});


/**
 * SQL definition for public.queries
 */
exports.queries = sql.define({
	name: 'queries',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'q' },
		{ name: 'oracle_options' },
		{ name: 'oracle_id' },
		{ name: 'territoire_id' }
	]
});


/**
 * SQL definition for public.query_results
 */
exports.query_results = sql.define({
	name: 'query_results',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'results' },
		{ name: 'query_id' }
	]
});


/**
 * SQL definition for public.resource_annotations
 */
exports.resource_annotations = sql.define({
	name: 'resource_annotations',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'resource_id' },
		{ name: 'territoire_id' },
		{ name: 'user_id' },
		{ name: 'expression_domain_id' },
		{ name: 'approved' },
		{ name: 'facebook_like' },
		{ name: 'facebook_share' },
		{ name: 'google_pagerank' },
		{ name: 'linkedin_share' },
		{ name: 'sentiment' },
		{ name: 'favorite' },
		{ name: 'tags' },
		{ name: 'publication_date' }
	]
});


/**
 * SQL definition for public.resources
 */
exports.resources = sql.define({
	name: 'resources',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'url' },
		{ name: 'alias_of' },
		{ name: 'expression_id' },
		{ name: 'http_status' },
		{ name: 'content_type' },
		{ name: 'other_error' }
	]
});


/**
 * SQL definition for public.tasks
 */
exports.tasks = sql.define({
	name: 'tasks',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'type' },
		{ name: 'resource_id' },
		{ name: 'territoire_id' },
		{ name: 'depth' },
		{ name: 'status' }
	]
});


/**
 * SQL definition for public.territoires
 */
exports.territoires = sql.define({
	name: 'territoires',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'description' },
		{ name: 'user_id' }
	]
});


/**
 * SQL definition for public.users
 */
exports.users = sql.define({
	name: 'users',
	columns: [
		{ name: 'created_at' },
		{ name: 'updated_at' },
		{ name: 'id' },
		{ name: 'name' },
		{ name: 'emails' },
		{ name: 'google_id' },
		{ name: 'google_name' },
		{ name: 'google_picture_url' }
	]
});


