app:
   build: .
   command: node server/index.js
   links:
      - db
      - elasticanalysis
   ports:
      - 3333:3333
   volumes:
      - ./config/google-credentials-stable.json:/usr/mywi/config/google-credentials.json
   environment:
      - POSTGRES_PASSWORD=password
      - NODE_ENV=experimental
db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=password
   volumes:
      - /etc/postgresql
      - /var/log/postgresql
      - /var/lib/postgresql
      - /var/lib/postgresql/data
   expose:
      - 5432:5432
elasticanalysis: 
   image: elasticsearch:1.7
   environment:
      - ELASTICSEARCH_USER=user
      - ELASTICSEARCH_PASS=password
   expose:
      - 9200